module Quake
    module Domain
        module KillType
            MOD_BFG_SPLASH = "MOD_BFG_SPLASH"
            MOD_BFG = "MOD_BFG"
            MOD_CHAINGUN = "MOD_CHAINGUN"
            MOD_CRUSH = "MOD_CRUSH"
            MOD_FALLING = "MOD_FALLING"
            MOD_GAUNTLET = "MOD_GAUNTLET"
            MOD_GRAPPL = "MOD_GRAPPL"
            MOD_GRENADE_SPLASH = "MOD_GRENADE_SPLASH"
            MOD_GRENADE = "MOD_GRENADE"
            MOD_JUICED = "MOD_JUICED"
            MOD_KAMIKAZE = "MOD_KAMIKAZE"
            MOD_LAVA = "MOD_LAVA"
            MOD_LIGHTNING = "MOD_LIGHTNING"
            MOD_MACHINEGUN = "MOD_MACHINEGUN"
            MOD_NAIL = "MOD_NAIL"
            MOD_PLASMA_SPLASH = "MOD_PLASMA_SPLASH"
            MOD_PLASMA = "MOD_PLASMA"
            MOD_PROXIMITY_MINE = "MOD_PROXIMITY_MINE"
            MOD_RAILGUN = "MOD_RAILGUN"
            MOD_ROCKET_SPLASH = "MOD_ROCKET_SPLASH"
            MOD_ROCKET = "MOD_ROCKET"
            MOD_SHOTGUN = "MOD_SHOTGUN"
            MOD_SLIME = "MOD_SLIME"
            MOD_SUICIDE = "MOD_SUICIDE"
            MOD_TARGET_LASER = "MOD_TARGET_LASER"
            MOD_TELEFRAG = "MOD_TELEFRAG"
            MOD_TRIGGER_HURT = "MOD_TRIGGER_HURT"
            MOD_UNKNOWN = "MOD_UNKNOWN"
            MOD_WATER = "MOD_WATER"
        end
    end
end
