require "json"

require_relative "./domain/Kill.rb"
require_relative "./domain/KillType.rb"
require_relative "./domain/Match.rb"
require_relative "./domain/MatchScore.rb"
require_relative "./domain/Player.rb"
require_relative "./infra/LogLine.rb"
require_relative "./infra/LogLineForConnect.rb"
require_relative "./infra/LogLineForKill.rb"
require_relative "./infra/LogLineForNewGame.rb"
require_relative "./infra/LogParser.rb"
require_relative "./view/JsonReporter.rb"
